### ISSUE TITLE
[HELP] - ERROR: 'NoneType'

### ISSUE THREAD

**Issue by peluho** [MyElectricalData/myelectricaldata_import#418]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description de la fonctionnalité**

Configuration myelectricaldata add-on - ERROR

**Type d'installation**
HassIO

**Version : 2023.9.2**

2023-09-21 23:11:58.026 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/query_power.py", line 68, in run
    interval_reading = meter_reading["interval_reading"]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2023-09-21 23:11:58.027 -    ERROR : 'NoneType' object is not subscriptable
2023-09-21 23:11:58.027 -    ERROR : Echec de la récupération des données.
2023-09-21 23:11:58.027 -    ERROR :  => MyElectricalData est indisponible.
2023-09-21 23:11:58.027 -    ERROR :  => 2017-09-24 -> 2020-09-23
2023-09-21 23:11:58.027 -     INFO : Récupération des données : 2020-09-22 => 2020-09-23
2023-09-21 23:11:58.035 -     INFO :  Chargement des données depuis MyElectricalData 2020-09-22 => 2020-09-23
2023-09-21 23:11:58.400 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/query_power.py", line 68, in run
    interval_reading = meter_reading["interval_reading"]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2023-09-21 23:11:58.400 -    ERROR : 'NoneType' object is not subscriptable
2023-09-21 23:11:58.401 -    ERROR : Echec de la récupération des données.
2023-09-21 23:11:58.401 -    ERROR :  => MyElectricalData est indisponible.
2023-09-21 23:11:58.401 -    ERROR :  => 2020-09-22 -> 2020-09-23

L'addon démarre sans problème dans HASS, cependant quelque chose ne fonctionne pas correctement, je ne sais pas si c'est à cause du problème avec l'API.

Auparavant, j'utilisais l'intégration Enedis de HACS, et aujourd'hui, elle a cessé de fonctionner... c'est pourquoi j'ai continué à enquêter et j'ai trouvé cet addon.

Je pense que cela pourrait être lié à la configuration, mais cela me semble étrange car l'addon démarre sans problème.

**Comment by ZaGaPonG** [comment]
Hello,

Même erreur ici aussi si ça peut aider:
`<html>
<body>


2023-09-21 21:47:38 | stdout | 2023-09-21 23:47:38.347 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ TERMINE ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- | -- | --
2023-09-21 21:47:38 | stdout | 2023-09-21 23:47:38.347 -     INFO :  => Toutes les données sont déjà en cache.
2023-09-21 21:47:38 | stdout | 2023-09-21 23:47:38.340 -     INFO : Récupération des données : 2020-09-22 => 2020-09-23
2023-09-21 21:47:38 | stdout | 2023-09-21 23:47:38.340 -    ERROR :  => 2017-09-24 -> 2020-09-23
2023-09-21 21:47:38 | stdout | 2023-09-21 23:47:38.340 -    ERROR :  => MyElectricalData est indisponible.
2023-09-21 21:47:38 | stdout | 2023-09-21 23:47:38.339 -    ERROR : Echec de la récupération des données.
2023-09-21 21:47:38 | stdout | 2023-09-21 23:47:38.339 -    ERROR : 'NoneType' object is not subscriptable
2023-09-21 21:47:38 | stdout | TypeError: 'NoneType' object is not subscriptable
2023-09-21 21:47:38 | stdout | ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
2023-09-21 21:47:38 | stdout | interval_reading = meter_reading["interval_reading"]
2023-09-21 21:47:38 | stdout | File "/app/models/query_power.py", line 68, in run
2023-09-21 21:47:38 | stdout | Traceback (most recent call last):
2023-09-21 21:47:38 | stdout | 2023-09-21 23:47:38.338 -    ERROR : 'NoneType' object is not subscriptable
2023-09-21 21:47:37 | stdout | 2023-09-21 23:47:37.744 -     INFO :  Chargement des données depuis MyElectricalData 2020-09-23 => 2023-09-23
2023-09-21 21:47:35 | stdout | 2023-09-21 23:47:35.392 -     INFO : Récupération des données : 2020-09-23 => 2023-09-23
2023-09-21 21:47:35 | stdout | 2023-09-21 23:47:35.384 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-09-21 21:47:35 | stdout | 2023-09-21 23:47:35.384 -     INFO : [XX] RÉCUPÉRATION DE LA PUISSANCE MAXIMUM JOURNALIÈRE :
2023-09-21 21:47:35 | stdout | 2023-09-21 23:47:35.384 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-09-21 21:47:35 | stdout | 2023-09-21 23:47:35.383 -     INFO : Récupération de la production détaillée désactivée sur le point de livraison
2023-09-21 21:47:35 | stdout | 2023-09-21 23:47:35.383 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-09-21 21:47:35 | stdout | 2023-09-21 23:47:35.383 -     INFO : [XXX] RÉCUPÉRATION DE LA PRODUCTION DÉTAILLÉE :
2023-09-21 21:47:35 | stdout | 2023-09-21 23:47:35.383 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-09-21 21:47:35 | stdout | 2023-09-21 23:47:35.383 -     INFO : Récupération de la production journalière désactivée sur le point de livraison
2023-09-21 21:47:35 | stdout | 2023-09-21 23:47:35.383 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-09-21 21:47:35 | stdout | 2023-09-21 23:47:35.383 -     INFO : [XXX] RÉCUPÉRATION DE LA PRODUCTION JOURNALIÈRE :
2023-09-21 21:47:35 | stdout | 2023-09-21 23:47:35.383 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-09-21 21:47:35 | stdout | 2023-09-21 23:47:35.383 -    ERROR : argument of type 'NoneType' is not iterable
2023-09-21 21:47:35 | stdout | 2023-09-21 23:47:35.383 -    ERROR : Erreur lors de la récupération de la consommation détaillée
2023-09-21 21:47:35 | stdout | TypeError: argument of type 'NoneType' is not iterable
2023-09-21 21:47:35 | stdout | ^^^^^^^^^^^^^^^^^^
2023-09-21 21:47:35 | stdout | if "exit" in response:
2023-09-21 21:47:35 | stdout | File "/app/models/query_detail.py", line 200, in get
2023-09-21 21:47:35 | stdout | Detail(headers=self.header_generate(), usage_point_id=usage_point_id).get()
2023-09-21 21:47:35 | stdout | File "/app/models/jobs.py", line 272, in run
2023-09-21 21:47:35 | stdout | run(self.usage_point_config)
2023-09-21 21:47:35 | stdout | File "/app/models/jobs.py", line 283, in get_consumption_detail
2023-09-21 21:47:35 | stdout | Traceback (most recent call last):
2023-09-21 21:47:35 | stdout | 2023-09-21 23:47:35.382 -    ERROR : 'NoneType' object is not subscriptable
2023-09-21 21:47:35 | stdout | TypeError: 'NoneType' object is not subscriptable
2023-09-21 21:47:35 | stdout | ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
2023-09-21 21:47:35 | stdout | for interval_reading in meter_reading["interval_reading"]:
2023-09-21 21:47:35 | stdout | File "/app/models/query_detail.py", line 120, in run
2023-09-21 21:47:35 | stdout | Traceback (most recent call last):
2023-09-21 21:47:35 | stdout | 2023-09-21 23:47:35.381 -    ERROR : 'NoneType' object is not subscriptable
2023-09-21 21:47:34 | stdout | 2023-09-21 23:47:34.974 -     INFO :  Chargement des données depuis MyElectricalData 2023-09-16 => 2023-09-23
2023-09-21 21:47:34 | stdout | 2023-09-21 23:47:34.973 -     INFO :  - 5759m absente du relevé.
2023-09-21 21:47:34 | stdout | 2023-09-21 23:47:34.944 -     INFO : Récupération des données : 2023-09-16 => 2023-09-23


</body>
</html>`

En complément:

- Dernière version de HA et de MyElectricData.
- Pas de problème au niveau du relevé de ma conso du 19/9
- Données disponibles chez Enedis
- API OK car relevé via un autre addon pour ma conso du 20/9

Merci encore pour le travail :)

**Comment by thibdj** [comment]
Même erreur de mon côté

**Comment by ZaGaPonG** [comment]
[https://github.com/MyElectricalData/myelectricaldata_import/issues/419#issuecomment-1732515533](url) wait and see :)

**Comment by pismache** [comment]
Même erreur de mon côté

**Comment by m4dm4rtig4n** [comment]
La date vient de passer au 9 octobre....
https://datahub-enedis.fr/mon-compte-tableau-de-bord/

**Comment by NZX-DeSiGN** [comment]
La maintenance à l'air d'être terminée depuis cette après-midi (plus de message sur https://datahub-enedis.fr/).
J'ai toujours l'erreur cependant, je suppose qu'il faut finaliser la bascule sur les api v5 avant que l'erreur ne disparaisse ?

**Comment by m4dm4rtig4n** [comment]
Effectivement, merci pour l'info :)
Ce matin c'était encore en maintenance...

J'ai fait la demande de changement d'URL à l'instant :)

**Comment by WarC0zes** [comment]
Bonjour @m4dm4rtig4n,
toujours en attente du traitement de ta demande ?
Je me doute que c'est pas des presser.

**Comment by hayvan96** [comment]
Le site enedis ce matin quand on tente la demande de consentement (jusqu'ici, j'avais un json direct à l'issue) : 
![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/37040583/b6634c38-bd15-4375-a145-0728bebaea23)

**Comment by m4dm4rtig4n** [comment]
Tjr HS , enedis n'a pas encore traité ma demande de changement....

**Comment by IPv777** [comment]
Still down, yup

**Comment by m4dm4rtig4n** [comment]
VIa la manip expliqué sur la Home Page, le service est fonctionnel :)
