### ISSUE TITLE
[BUG] - Can't install ghcr.io/alexbelgium/myelectricaldata-amd64:0.9.2: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=0.9.2&fromImage=ghcr.io%2Falexbelgium%2Fmyelectricaldata-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

### ISSUE THREAD

**Issue by Jeepmg** [MyElectricalData/myelectricaldata_import#419]
**Description du bug**
Mise à jour en 0.9.2 impossible

Can't install ghcr.io/alexbelgium/myelectricaldata-amd64:0.9.2: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=0.9.2&fromImage=ghcr.io%2Falexbelgium%2Fmyelectricaldata-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
RENSEIGNE TON FICHIER DE CONFIG SANS PDL & TOKEN
```
</details>

**Type d'installation**

 HassIO

**Version : X.X.X**

Et aucunes données ne remontent depuis le 18/09

**Comment by Jeepmg** [comment]
@alexbelgium Can't install ghcr.io/alexbelgium/myelectricaldata-amd64:0.9.2: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=0.9.2&fromImage=ghcr.io%2Falexbelgium%2Fmyelectricaldata-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown") #419

J'ai ce message lorsque je veux effectuer mise à jour vers 0.9.2

**Comment by Arstrak** [comment]
Bonjour,

Même erreur pour moi

 Home Assistant 2023.9.2 Supervisor 2023.09.2 Operating System 10.5 Interface utilisateur : 20230911.0 - latest

**Comment by DoNuTs02** [comment]
même erreur !

**Comment by Userfreedu42** [comment]
Pareil aussi pour moi

**Comment by alexbelgium** [comment]
Bonjour, un bug semble en cours sur codenotary utilisé pour signer les images : https://github.com/alexbelgium/hassio-addons/issues/1000

Je vais annuler les updates et relancer les builds demain

**Comment by Jeepmg** [comment]
> Bonjour, un bug semble en cours sur codenotary utilisé pour signer les images : [alexbelgium/hassio-addons#1000](https://github.com/alexbelgium/hassio-addons/issues/1000)
> 
> Je vais annuler les updates et relancer les builds demain

Mise à jour fonctionne parfaitement. Merci

Par contre toujours pas de remontées d'info depuis le 19. Si je me réfère au forum des autres plugins faisant la même chose, ils ne semblent pas connaître ce souci.

**Comment by valderaplets** [comment]
> Mise à jour fonctionne parfaitement. Merci

Je confirme !

> Par contre toujours pas de remontées d'info depuis le 19. Si je me réfère au forum des autres plugins faisant la même chose, ils ne semblent pas connaître ce souci.

La même :(

**Comment by m4dm4rtig4n** [comment]
La remonte d'information est impossible pour l'instant car je soit changer une configuration sur l'interface pour finaliser la bascule sur les api v5 et l'interface chez enedis est en maintenance jusqu'au 25...

**Comment by ZaGaPonG** [comment]
Maintenance étendue jusq'au 29/9 -_-

**Comment by Jeepmg** [comment]
Non jusqu'au 3 et peut-etre plus si la date continue a être repoussée. Mais ca n'empêche pas normalement la remontée des consommations.

**Comment by m4dm4rtig4n** [comment]
> Non jusqu'au 3 et peut-etre plus si la date continue a être repoussée. Mais ca n'empêche pas normalement la remontée des consommations.

Ca ne bloque pas la remontée de consommation mais je ne peut pas finaliser la migration vers la v5 sans l'accès au portail ..

**Comment by valderaplets** [comment]
J'ai quand même 0 consommation depuis une bonne semaine avec ça :

```
2023-09-30 10:02:53.340 -     INFO : [XXXXX] RÉCUPÉRATION DE LA CONSOMMATION JOURNALIÈRE :
2023-09-30 10:02:53.341 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-09-30 10:02:53.389 -     INFO : Récupération des données : 2023-02-01 => 2023-10-02
2023-09-30 10:02:56.045 -     INFO :  Chargement des données depuis MyElectricalData 2023-02-01 => 2023-10-02
2023-09-30 10:02:56.837 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/query_daily.py", line 101, in run
    interval_reading = meter_reading["interval_reading"]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2023-09-30 10:02:56.842 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/jobs.py", line 259, in get_consumption
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 248, in run
    Daily(headers=self.header_generate(), usage_point_id=usage_point_id).get()
  File "/app/models/query_daily.py", line 168, in get
    if "exit" in response:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-09-30 10:02:56.848 -    ERROR : Erreur lors de la récupération de la consommation journalière
2023-09-30 10:02:56.848 -    ERROR : argument of type 'NoneType' is not iterable
2023-09-30 10:02:56.849 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-09-30 10:02:56.849 -     INFO : [XXXXX] RÉCUPÉRATION DE LA CONSOMMATION DÉTAILLÉE :
2023-09-30 10:02:56.849 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-09-30 10:02:56.879 -     INFO : Récupération des données : 2023-09-25 => 2023-10-02
2023-09-30 10:02:56.968 -     INFO :  - 11519m absente du relevé.
2023-09-30 10:02:56.968 -     INFO :  Chargement des données depuis MyElectricalData 2023-09-25 => 2023-10-02
2023-09-30 10:02:57.691 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/query_detail.py", line 120, in run
    for interval_reading in meter_reading["interval_reading"]:
                            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2023-09-30 10:02:57.695 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/jobs.py", line 283, in get_consumption_detail
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 272, in run
    Detail(headers=self.header_generate(), usage_point_id=usage_point_id).get()
  File "/app/models/query_detail.py", line 200, in get
    if "exit" in response:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-09-30 10:02:57.698 -    ERROR : Erreur lors de la récupération de la consommation détaillée
2023-09-30 10:02:57.698 -    ERROR : argument of type 'NoneType' is not iterable
2023-09-30 10:02:57.699 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by m4dm4rtig4n** [comment]
Le soucis avec l'addon est réglé, le soucis d'indispo de la passerelle est tt autres.
Je clos le ticket.

**Comment by thibdj** [comment]
@m4dm4rtig4n j'ai tjrs le problème 


```
2023-10-04 19:10:06.203 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/query_daily.py", line 101, in run
    interval_reading = meter_reading["interval_reading"]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2023-10-04 19:10:06.206 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/jobs.py", line 259, in get_consumption
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 248, in run
    Daily(headers=self.header_generate(), usage_point_id=usage_point_id).get()
  File "/app/models/query_daily.py", line 168, in get
    if "exit" in response:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-10-04 19:10:06.211 -    ERROR : Erreur lors de la récupération de la consommation journalière
2023-10-04 19:10:06.211 -    ERROR : argument of type 'NoneType' is not iterable
```

**Comment by m4dm4rtig4n** [comment]
Normal le service enedis est tjr HS, le soucis ne vient pas de l'addon.

**Comment by Jeepmg** [comment]
> Ca ne bloque pas la remontée de consommation mais je ne peut pas finaliser la migration vers la v5 sans l'accès au portail ..

Il s’avère qu’en pratique les données remontent toujours correctement depuis l’api V4. Dommage.
