### ISSUE TITLE
[BUG] - Récupération de la consommation détaillée KO

### ISSUE THREAD

**Issue by floow77** [MyElectricalData/myelectricaldata_import#426]
**Description du bug**

```
2023-10-21 13:59:05.980 -     INFO : [22149782812540] RÉCUPÉRATION DE LA CONSOMMATION DÉTAILLÉE :
2023-10-21 13:59:05.980 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-10-21 13:59:05.996 -     INFO : Récupération des données : 2023-10-16 => 2023-10-23
2023-10-21 13:59:06.068 -     INFO :  - 5759m absente du relevé.
2023-10-21 13:59:06.069 -     INFO :  Chargement des données depuis MyElectricalData 2023-10-16 => 2023-10-23
2023-10-21 13:59:06.695 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/query_detail.py", line 120, in run
    for interval_reading in meter_reading["interval_reading"]:
                            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2023-10-21 13:59:06.697 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/jobs.py", line 283, in get_consumption_detail
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 272, in run
    Detail(headers=self.header_generate(), usage_point_id=usage_point_id).get()
  File "/app/models/query_detail.py", line 200, in get
    if "exit" in response:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-10-21 13:59:06.699 -    ERROR : Erreur lors de la récupération de la consommation détaillée
2023-10-21 13:59:06.699 -    ERROR : argument of type 'NoneType' is not iterable
2023-10-21 13:59:06.699 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ 

```
<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400 
debug: true
wipe_influxdb: true
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: ha
influxdb:
  enable: false
  hostname: influx
  port: 8086
  token: ha:ha
  org: "-"
  bucket: "enedis/autogen" 
  asynchronous: "false"
  batching_options:
    batch_size: 1000
    flush_interval: 1000
    jitter_interval: 0
    retry_interval: 5000
    max_retry_time: 180_000
    max_retries: 5
    max_retry_delay: 125_000
    exponential_base: 2
mqtt:
  enable: true
  hostname: core-mosquitto
  port: 1883
  username: "mqtt"
  password: "mqtt"
  prefix: myelectricaldata
  client_id: myelectricaldata # DOIT ETRE UNIQUE SUR LA TOTALITE DES CLIENTS CONNECTE AU SERVEUR MQTT
  retain: true
  qos: 0
myelectricaldata:
  "12349782123123":
    enable: "true"
    token: 473NMrsrrsyrgfsgsd # Date du dernier renouvellement: 20/10/2023
    name: "Maison"
    addresses: "true"
    cache: "true"
    consumption: "true"
    consumption_detail: "true"
    consumption_price_base: "0.1740" 
    consumption_price_hc: "0.1330"
    consumption_price_hp: "0.1936" 
    consumption_max_date: "2021-07-03"
    consumption_detail_max_date: "2021-07-03"
    offpeak_hours_0: 01H36-8H06;12H06-13H36 # LUNDI
    offpeak_hours_1: 01H36-8H06;12H06-13H36 # MARDI
    offpeak_hours_2: 01H36-8H06;12H06-13H36 # MERCREDI
    offpeak_hours_3: 01H36-8H06;12H06-13H36 # JEUDI
    offpeak_hours_4: 01H36-8H06;12H06-13H36 # VENDREDI
    offpeak_hours_5: 01H36-8H06;12H06-13H36 # SAMEDI
    offpeak_hours_6: 01H36-8H06;12H06-13H36 # DIMANCHE
    plan: HC/HP
    production: "false"
    production_detail: "false"
    production_price: "0.0"
    production_max_date: "2021-06-01"
    production_detail_max_date: "2021-06-01"
    refresh_addresse: "false"
    refresh_contract: "false"

```
</details>

**Type d'installation**
- [ ] HassIO

**Home Assistant 2023.10.3**
Supervisor 2023.10.0
Operating System 11.0
Interface utilisateur : 20231005.0 - latest

**Comment by m4dm4rtig4n** [comment]
Hello @floow77 ,

Le soucis est encore d'actualité ?

**Comment by wallforfry** [comment]
Hello @m4dm4rtig4n !
J'ai le même soucis depuis le 1er décembre même stacktrace

```
2024-01-12 11:20:20.228 -     INFO :  Chargement des données depuis MyElectricalData 2023-12-31 => 2024-01-07
2024-01-12 11:20:54.357 -    ERROR : Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/models/query_detail.py", line 159, in run
    "description": json.loads(data.text)["detail"],
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-01-12 11:20:54.380 -    ERROR : Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/models/jobs.py", line 283, in get_consumption_detail
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 272, in run
    Detail(headers=self.header_generate(), usage_point_id=usage_point_id).get()
  File "/app/models/query_detail.py", line 200, in get
    if "exit" in response:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2024-01-12 11:20:54.381 -    ERROR : Erreur lors de la récupération de la consommation détaillée
```
