### ISSUE TITLE
[BUG] - Erreur TEMPO empêche export vers MQTT

### ISSUE THREAD

**Issue by vingerha** [MyElectricalData/myelectricaldata_import#427]
MED v092
Docker

```
2023-10-29 07:00:10.776 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-10-29 07:00:10.777 -     INFO : [xxxx] EXPORTATION DES DONNÉES VERS HOME ASSISTANT (VIA MQTT)
2023-10-29 07:00:10.777 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-10-29 07:17:23.354 -     INFO : Consommation :
2023-10-29 07:17:24.903 -     INFO : tempo BEGIN: 2023-10-28 00:00:00
2023-10-29 07:17:24.903 -     INFO : tempo END: 2023-10-28 23:59:59.999999
2023-10-29 07:17:24.944 -     INFO : tempo data: ConsumptionDetail(id='fea7b950702b8e4f588f09cd6435bf49', usage_point_id='xxxx', date=datetime.datetime(2023, 10, 28, 23, 30),value=654, interval=30, measure_type='HC', blacklist=0, fail_count=0)
2023-10-29 07:17:24.944 -     INFO : tempo hour: 23
Traceback (most recent call last):
  File "/app/models/jobs.py", line 435, in export_home_assistant
    run(self.usage_point_config, target)
  File "/app/models/jobs.py", line 422, in run
    HomeAssistant(usage_point_id).export()
  File "/app/models/export_home_assistant.py", line 93, in export
    self.myelectricaldata_usage_point_id("consumption")
  File "/app/models/export_home_assistant.py", line 385, in myelectricaldata_usage_point_id
    tempo_data = stats.tempo(i)["value"]
                 ^^^^^^^^^^^^^^
  File "/app/models/stat.py", line 104, in tempo
    color = self.db.get_tempo_range(begin + timedelta(days=1), end + timedelta(days=1))[0].color
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2023-10-29 07:00:12.423 -    ERROR : Erreur lors de l'exportation des données vers home assistant (via mqtt)
2023-10-29 07:00:12.423 -    ERROR : list index out of range
```

**Comment by m4dm4rtig4n** [comment]
Soucis Fix dans la 0.9.3.b1 normalement.

**Comment by vingerha** [comment]
J'ai testé b1 sur mon truc HAOS... erreur dessous, j'ai viré cache.db et redémarré...même erreur
```
2023-11-07 09:15:13.895 -    ERROR : Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/routers/html.py", line 22, in main
    return Index(CONFIG, DB).display()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/index.py", line 39, in display
    select_usage_points=self.usage_point_select.html(),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/models/usage_point_select.py", line 20, in html
    for config in self.db.get_usage_point_all():
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/models/database.py", line 246, in get_usage_point_all
    data = self.session.scalars(query).all()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in scalars
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1771, in scalars
    return self.execute(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT usage_points.usage_point_id, usage_points.name, usage_points.cache, usage_points.consumption, usage_points.consumption_detail, usage_points.production, usage_points.production_detail, usage_points.consumption_price_base, usage_points.consumption_price_hc, usage_points.consumption_price_hp, usage_points.production_price, usage_points.offpeak_hours_0, usage_points.offpeak_hours_1, usage_points.offpeak_hours_2, usage_points.offpeak_hours_3, usage_points.offpeak_hours_4, usage_points.offpeak_hours_5, usage_points.offpeak_hours_6, usage_points."plan", usage_points.refresh_addresse, usage_points.refresh_contract, usage_points.token, usage_points.progress, usage_points.progress_status, usage_points.enable, usage_points.consentement_expiration, usage_points.call_number, usage_points.quota_reached, usage_points.quota_limit, usage_points.quota_reset_at, usage_points.last_call, usage_points.ban, usage_points.consumption_max_date, usage_points.consumption_detail_max_date, usage_points.production_max_date, usage_points.production_detail_max_date, usage_points.consumption_max_power, usage_points.last_error 
FROM usage_points]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by m4dm4rtig4n** [comment]
Tu as encore le soucis @vingerha ?

**Comment by vingerha** [comment]
Oublié...fermé

**Comment by pvince83** [comment]
J’ai la meme erreur depuis hier. Comment passer en 0.9.3 le repo est tjs en 0.9.2-6?
