### ISSUE TITLE
[BUG] - Erreur après recupération production

### ISSUE THREAD

**Issue by ioniks** [MyElectricalData/myelectricaldata_import#443]
**Description du bug**
J'ai l'intégration qui fonctionne sur docker (dernier version) depuis presque un an, j'ai eu la mise en service de la production et les données se récupère bien visiblement. Je suis aussi passé en TEMPO aujourd'hui (mais le problème se poser avant)

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
myelectricaldata:
  'XXXXXXXXXXXXX':
    activation_date_daily: ''
    activation_date_detail: ''
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_max_power: 'true'
    consumption_price_base: '0.2276'
    consumption_price_hc: '0.1828'
    consumption_price_hp: '0.246'
    enable: 'true'
    name: Maison
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: 'true'
    production_detail: 'true'
    production_detail_max_date: '2023-12-05'
    production_max_date: '2023-12-05'
    production_price: '0.1339'
    refresh_addresse: 'true'
    refresh_contract: 'true'
    token: XXXXXXXXXXXXXXXXXXXXX
```
</details>

<details>
<summary>Detail erreur a l'ouverture de la page</summary>
```
2023-12-07 11:25:28.640 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-12-07 11:25:28.640 -     INFO : REFRESH ORM OBJECTS
2023-12-07 11:25:28.640 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-12-07 11:25:29.751 -     INFO : 192.168.0.10:54977 - "GET /usage_point_id/XXXXXXXHTTP/1.1" 500
2023-12-07 11:25:29.751 -    ERROR : Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/routers/html.py", line 28, in usage_point_id
    return UsagePoint(usage_point_id).display()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 335, in display
    self.consumption_vs_production(year)
  File "/app/templates/usage_point.py", line 723, in consumption_vs_production
    for month, value in self.recap_production_data[year]["month"].items():
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: '2022'
```
</details>

**Type d'installation**
Docker

**Version : latest**

**Comment by koukihai** [comment]
``` 
2023-12-07 11:25:28.640 - INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 
2023-12-07 11:25:28.640 - INFO : REFRESH ORM OBJECTS
2023-12-07 11:25:28.640 - INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 
2023-12-07 11:25:29.751 - INFO : 192.168.0.10:54977 - "GET /usage_point_id/16164688707486 HTTP/1.1" 500 
2023-12-07 11:25:29.751 - ERROR : Exception in ASGI application 
Traceback (most recent call last):
 File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
   result = await app( # type: ignore[func-returns-value] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
   return await self.app(scope, receive, send) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
   await super().__call__(scope, receive, send)
 File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
   await self.middleware_stack(scope, receive, send)
 File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__ 
  raise exc
 File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
   await self.app(scope, receive, _send)
 File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
   raise exc
 File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
   await self.app(scope, receive, sender)
 File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
   raise e
 File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
   await self.app(scope, receive, send)
 File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
   await route.handle(scope, receive, send)
 File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
   await self.app(scope, receive, send)
 File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
   response = await func(request) ^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
   raw_response = await run_endpoint_function( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
   return await run_in_threadpool(dependant.call, **values) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
   return await anyio.to_thread.run_sync(func, *args) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
   return await get_asynclib().run_sync_in_worker_thread( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
   return await future ^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
   result = context.run(func, *args) ^^^^^^^^^^^^^^^^^^^^^^^^
 File "/app/routers/html.py", line 28, in usage_point_id
   return UsagePoint(usage_point_id).display() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/app/templates/usage_point.py", line 335, in display
   self.consumption_vs_production(year)
 File "/app/templates/usage_point.py", line 723, in consumption_vs_production
   for month, value in self.recap_production_data[year]["month"].items():
   ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^ KeyError: '2022' 
``` 

Si je comprends bien le probleme, l'application tente de comparer les donnees de production et de consommation de 2022. Or j'imagine que la production ne fonctionnait pas en 2022, ce qui declenche un bug dans l'application.

Je propose un fix ici: https://github.com/MyElectricalData/myelectricaldata_import/pull/458

**Comment by ioniks** [comment]
avec ce fix ça donne ça :
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/routers/html.py", line 28, in usage_point_id
    return UsagePoint(usage_point_id).display()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 335, in display
    self.consumption_vs_production(year)
  File "/app/templates/usage_point.py", line 723, in consumption_vs_production
    consumption_months = []
                        ^^^^
KeyError: '2022'
```

**Comment by koukihai** [comment]
A voir l'erreur, il semble y avoir une incoherence entre ce que l'appli execute et ce qu'il y a sur le disque. Une "KeyError" ne peut pas etre renvoyee par une liste, vide qui plus est.

Est-ce que tu as simplement copie le fichier dans ton repertoire `/app`? 

Si oui, je pense qu'il faut redemarrer uvicorn pour qu'il prenne en compte les nouveaux fichiers. 
Cependant, malgre mes recherches, je ne trouve pas de "soft-restart" pour uvicorn.

J'ai preparé une image avec `myelectricaldata_import:master` + le fix.

**Avertissement**: Je ne peux pas t'assurer que toutes les fonctionnalites soient operationnelles sur `master` que j'utilise comme base pour mon fix. Je te conseille de faire un backup de ta db si tu decides de deployer cette image.
<details>
<summary> J'ai lu l'avertissement </summary> 

Voici l'image: `ghcr.io/koukihai/myelectricaldata_import:issue-443`
Pour info, l'image a ete generee avec cette action: https://github.com/koukihai/myelectricaldata_import/actions/runs/7438470934/job/20237259763
</details>

**Comment by ioniks** [comment]
Avec l'image que tu as compilé pour l'erreur cela fonctionne, j'ai mon détail de production qui reste vide, mais les relevé journalier sont affiché et aucune erreur ;)

**Comment by koukihai** [comment]
C'est une bonne nouvelle ! 🎉 
De ce que je comprends, le probleme est cependant pas completement resolu. 😅 

En ce qui concerne le detail de production qui reste vide... je vais devoir debugger a l'aveugle, je fais que consommer 😅 

* Est-ce que le detail de production reste vide peu importe le mois et l'annee?
* Est-ce que tu aurais des logs concernant la recuperation des donnees de production? 

Ou eventuellement partager le resultat de la requete suivante:
```
select date, measure_type, value from production_detail order by date desc limit 10;
```

Si tu souhaites l'executer a l'interieur de ton container, tu peux faire ca:
```
python -c "import sqlite3; c = sqlite3.connect('/data/cache.db'); print(c.execute('select date, measure_type, value from production_detail order by date desc limit 10;').fetchall())"
```

**Comment by ioniks** [comment]
La table est tout simplement vide alors qu'avec l'ancienne version j'avais des infos dedans.

```
2024-01-08 14:55:46.372 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-01-08 14:55:46.372 -     INFO : ▌│█║▌║▌║                              Point de livraison : XXXXXXXXX                              ║▌║▌║█│▌
2024-01-08 14:55:46.372 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-01-08 14:55:46.396 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-01-08 14:55:46.396 -     INFO : [XXXXXXXXX] RÉCUPÉRATION DE LA PRODUCTION DÉTAILLÉE :
2024-01-08 14:55:46.397 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-01-08 14:55:46.403 -     INFO : Récupération des données : 2024-01-03 => 2024-01-10
2024-01-08 14:55:46.406 -     INFO :  - 11519m absente du relevé.
2024-01-08 14:55:46.406 -     INFO :  Chargement des données depuis MyElectricalData 2024-01-03 => 2024-01-10
2024-01-08 14:56:46.643 -    ERROR : HTTPSConnectionPool(host='myelectricaldata.fr', port=443): Read timed out. (read timeout=60)
2024-01-08 14:56:46.643 -    ERROR : Echec de la récupération des données.
2024-01-08 14:56:46.644 -    ERROR :  => {}
2024-01-08 14:56:46.644 -    ERROR :  => 2023-12-27 -> 2024-01-03
2024-01-08 14:56:46.644 -     INFO : Récupération des données : 2023-12-27 => 2024-01-03
2024-01-08 14:56:46.654 -     INFO :  - 11519m absente du relevé.
2024-01-08 14:56:46.654 -     INFO :  Chargement des données depuis MyElectricalData 2023-12-27 => 2024-01-03
2024-01-08 14:56:49.366 -     INFO : Récupération des données : 2023-12-20 => 2023-12-27
2024-01-08 14:56:49.370 -     INFO :  - 11519m absente du relevé.
2024-01-08 14:56:49.370 -     INFO :  Chargement des données depuis MyElectricalData 2023-12-20 => 2023-12-27
2024-01-08 14:56:52.049 -     INFO : Récupération des données : 2023-12-13 => 2023-12-20
2024-01-08 14:56:52.052 -     INFO :  - 11519m absente du relevé.
2024-01-08 14:56:52.053 -     INFO :  Chargement des données depuis MyElectricalData 2023-12-13 => 2023-12-20
2024-01-08 14:56:54.828 -     INFO : Récupération des données : 2023-12-06 => 2023-12-13
2024-01-08 14:56:54.832 -     INFO :  - 11519m absente du relevé.
2024-01-08 14:56:54.832 -     INFO :  Chargement des données depuis MyElectricalData 2023-12-06 => 2023-12-13
2024-01-08 14:56:57.782 -     INFO : Récupération des données : 2023-12-05 => 2023-12-06
2024-01-08 14:56:57.786 -     INFO :  - 2879m absente du relevé.
2024-01-08 14:56:57.786 -     INFO :  Chargement des données depuis MyElectricalData 2023-12-05 => 2023-12-06
2024-01-08 14:57:59.041 -    ERROR : HTTPSConnectionPool(host='myelectricaldata.fr', port=443): Read timed out. (read timeout=60)
2024-01-08 14:57:59.041 -    ERROR : Echec de la récupération des données.
2024-01-08 14:57:59.042 -    ERROR :  => {}
2024-01-08 14:57:59.042 -    ERROR :  => 2023-12-05 -> 2023-12-06
2024-01-08 14:57:59.042 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ TERMINE ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-01-08 14:57:59.043 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-01-08 14:57:59.043 -     INFO : ▌│█║▌║▌║       ___                                 _     _____  _         _       _      _  _  _       ║▌║▌║█│▌
2024-01-08 14:57:59.043 -     INFO : ▌│█║▌║▌║      |_ _| _ __ ___   _ __    ___   _ __ | |_  |  ___|(_) _ __  (_) ___ | |__  | || || |      ║▌║▌║█│▌
2024-01-08 14:57:59.043 -     INFO : ▌│█║▌║▌║       | | | '_ ` _ \ | '_ \  / _ \ | '__|| __| | |_   | || '_ \ | |/ __|| '_ \ | || || |      ║▌║▌║█│▌
2024-01-08 14:57:59.043 -     INFO : ▌│█║▌║▌║       | | | | | | | || |_) || (_) || |   | |_  |  _|  | || | | || |\__ \| | | ||_||_||_|      ║▌║▌║█│▌
2024-01-08 14:57:59.044 -     INFO : ▌│█║▌║▌║      |___||_| |_| |_|| .__/  \___/ |_|    \__| |_|    |_||_| |_||_||___/|_| |_|(_)(_)(_)      ║▌║▌║█│▌
2024-01-08 14:57:59.044 -     INFO : ▌│█║▌║▌║                      |_|                                                                      ║▌║▌║█│▌
2024-01-08 14:57:59.044 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by koukihai** [comment]
Je crois avoir trouve quelque chose 💡 
J'ai pousse un nouveau fix dans ma branche, et voici l'image contenant ce nouveau fix
<details><summary>J'ai re-lu l'avertissement 😅 </summary>

Voici l'image: `ghcr.io/koukihai/myelectricaldata_import:issue-443-2`

Construite a partir de l'action suivante: https://github.com/koukihai/myelectricaldata_import/actions/runs/7454006788/job/20280495838
</details>

**Comment by ioniks** [comment]
Je te confirme que maintenant cela fonctionne ;) Merci

Dis moi quand c'est merge sur master que je revienne a l'image principal :)

**Comment by koukihai** [comment]
Merci d'avoir testé aussi vite! 🙇 
Je connais pas le cycle de release, du coup je saurais pas te dire quand est-ce que le fix sera disponible 😅 

Et si je me trompe pas, il y'aura ptet un peu de nettoyage a faire dans ta db: a cause du bug, les donnees de consommation et de production etaient melangees dans la table de consommation.
Il y a probablement un moyen de forcer un refresh a partir d'une certaine date, mais je connais trop peu l'application pour te dire comment faire 😞

**Comment by ioniks** [comment]
Ok ça marche.

Tu peux éditer ta première réponse et supprimer l'identifiant de mon PDL dans le lien ;)

Merci

**Comment by m4dm4rtig4n** [comment]
Je clos l'issue car merge dans la 0.10.0 :)
