### ISSUE TITLE
[BUG] - Erreur No module named 'pytz'

### ISSUE THREAD

**Issue by Alindil** [MyElectricalData/myelectricaldata_import#470]
**Description du bug**
Depuis l'installation de la dernière version V 0.9.3, l'appli ne démarre plus.
J'ai cette erreur dans les traces:

2024-01-25 09:17:40.103 -     INFO : Configure Databases
2024-01-25 09:17:40.181 -     INFO :  => day
2024-01-25 09:17:40.188 -     INFO :  => call_number
2024-01-25 09:17:40.193 -     INFO :  => max_call
2024-01-25 09:17:40.198 -     INFO :  => version
2024-01-25 09:17:40.203 -     INFO :  => lock
2024-01-25 09:17:40.207 -     INFO :  => lastUpdate
2024-01-25 09:17:40.208 -     INFO :  Success
2024-01-25 09:17:40.208 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-01-25 09:17:40.208 -     INFO : Connect to MQTT broker 10.0.4.3:1883
2024-01-25 09:17:40.216 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-01-25 09:17:40.217 -     INFO : CONNECTION SUCCESS
2024-01-25 09:17:40.217 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Traceback (most recent call last):
  File "/app/main.py", line 13, in <module>
    from models.jobs import Job
  File "/app/models/jobs.py", line 15, in <module>
    from models.export_home_assistant import HomeAssistant
  File "/app/models/export_home_assistant.py", line 5, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'

<details>
<summary>Configuration (config.yaml)</summary>

cycle: 14400
debug: true
home_assistant:
  discovery_prefix: homeassistant
  enable: true
influxdb:
  batching_options:
    batch_size: 1000
    exponential_base: 2
    flush_interval: 1000
    jitter_interval: 0
    max_retries: 5
    max_retry_delay: 125000
    max_retry_time: 180000
    retry_interval: 5000
  bucket: myelectricaldata
  enable: false
  hostname: influxdb
  method: synchronous
  org: myelectricaldata
  port: 8086
  token: myelectricaldata
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: 10.0.4.3
  password: XXX
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: XXX
myelectricaldata:
  'XXX':
    activation_date_daily: '2022-01-01'
    activation_date_detail: '2022-01-01'
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: '2022-01-01'
    consumption_max_date: '2022-01-01'
    consumption_max_power: 'true'
    consumption_price_base: '0.15408'
    consumption_price_hc: '0.15408'
    consumption_price_hp: '0.15408'
    enable: 'true'
    name: Maison
    offpeak_hours_0: 22h30-06h30
    offpeak_hours_1: 22h30-06h30
    offpeak_hours_2: 22h30-06h30
    offpeak_hours_3: 22h30-06h30
    offpeak_hours_4: 22h30-06h30
    offpeak_hours_5: 22h30-06h30
    offpeak_hours_6: 22h30-06h30
    plan: BASE
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: '2022-01-01'
    production_max_date: '2022-01-01'
    production_price: '0.0'
    refresh_addresse: 'false'
    refresh_contract: 'false'
    token: XXX
wipe_influxdb: false
</details>

**Type d'installation**

- [X] Docker
- [ ] HassIO

**Version : 0.9.3**

**Comment by LightD31** [comment]
J'ai le même soucis

**Comment by m4dm4rtig4n** [comment]
Normalement c'est fix dans la 0.10.0-rc.19

**Comment by pbranly** [comment]
Oui ça fonctionne dans la rc19

**Comment by m4dm4rtig4n** [comment]
@Alindil le soucis sur la 0.9.3 était un build foireux de ma part.
La 0.9.3 est revenu dans son état initial.
