### ISSUE TITLE
[BUG] - ERROR : Exception in ASGI application

### ISSUE THREAD

**Issue by Gandulf78** [MyElectricalData/myelectricaldata_import#479]
**Description du bug**
Internal Server Error systématique en essayant d'ouvrir le dashboard.

Logs avec l'erreur:

```
2024-02-02 23:02:14.126 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-02 23:02:14.126 -     INFO : RÉCUPÉRATION DU STATUT DE LA PASSERELLE :
2024-02-02 23:02:14.127 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-02 23:02:14.293 -     INFO : status: True
2024-02-02 23:02:14.293 -     INFO : information: None
2024-02-02 23:02:14.293 -     INFO : nb_client: 2166
2024-02-02 23:02:14.293 -     INFO : waiting_estimation: 0.0s
2024-02-02 23:05:48.727 -     INFO : 172.28.0.3:59132 - "GET / HTTP/1.1" 200
2024-02-02 23:05:48.967 -     INFO : 172.28.0.3:59144 - "GET /static/css/popup.css HTTP/1.1" 304
2024-02-02 23:05:48.969 -     INFO : 172.28.0.3:59150 - "GET /static/css/notif.css HTTP/1.1" 304
2024-02-02 23:05:48.970 -     INFO : 172.28.0.3:59162 - "GET /static/css/nice-select.css HTTP/1.1" 304
2024-02-02 23:05:48.971 -     INFO : 172.28.0.3:59158 - "GET /static/js/menu.js HTTP/1.1" 304
2024-02-02 23:05:48.973 -     INFO : 172.28.0.3:59132 - "GET /static/js/notif.js HTTP/1.1" 304
2024-02-02 23:05:48.974 -     INFO : 172.28.0.3:59152 - "GET /static/css/logo.css HTTP/1.1" 304
2024-02-02 23:05:48.975 -     INFO : 172.28.0.3:59148 - "GET /static/css/main.css HTTP/1.1" 304
2024-02-02 23:05:48.976 -     INFO : 172.28.0.3:59166 - "GET /static/css/menu.css HTTP/1.1" 304
2024-02-02 23:05:48.976 -     INFO : 172.28.0.3:59154 - "GET /static/js/nice-select.js HTTP/1.1" 304
2024-02-02 23:05:48.977 -     INFO : 172.28.0.3:59142 - "GET /static/js/jquery-fab-button.min.js HTTP/1.1" 304
2024-02-02 23:05:48.978 -     INFO : 172.28.0.3:59156 - "GET /static/js/validator_fr.js HTTP/1.1" 304
2024-02-02 23:05:48.979 -     INFO : 172.28.0.3:59146 - "GET /static/js/popup.js HTTP/1.1" 304
2024-02-02 23:05:48.979 -     INFO : 172.28.0.3:59138 - "GET /static/css/jquery-fab-button.min.css HTTP/1.1" 304
2024-02-02 23:05:48.980 -     INFO : 172.28.0.3:59160 - "GET /static/img/discord.png HTTP/1.1" 304
2024-02-02 23:05:48.981 -     INFO : 172.28.0.3:59140 - "GET /static/img/paypal.png HTTP/1.1" 304
2024-02-02 23:05:48.981 -     INFO : 172.28.0.3:59164 - "GET /static/img/enedis.png HTTP/1.1" 304
2024-02-02 23:05:48.982 -     INFO : 172.28.0.3:59136 - "GET /static/img/icon.svg HTTP/1.1" 304
2024-02-02 23:05:48.982 -     INFO : 172.28.0.3:59168 - "GET /static/img/loading.gif HTTP/1.1" 304
2024-02-02 23:05:49.284 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-02 23:05:49.284 -     INFO : CHECK DE L'ÉTAT DE LA PASSERELLE.
2024-02-02 23:05:49.284 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-02 23:05:49.604 -     INFO : status: True
2024-02-02 23:05:49.604 -     INFO : information: None
2024-02-02 23:05:49.604 -     INFO : nb_client: 2166
2024-02-02 23:05:49.604 -     INFO : waiting_estimation: 0.0s
2024-02-02 23:05:49.662 -     INFO : 172.28.0.3:59168 - "GET /gateway_status/ HTTP/1.1" 200
2024-02-02 23:05:52.099 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-02 23:05:52.100 -     INFO : REFRESH ORM OBJECTS
2024-02-02 23:05:52.100 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-02 23:05:52.944 -     INFO : 172.28.0.3:59168 - "GET /usage_point_id/50067238117598 HTTP/1.1" 500
2024-02-02 23:05:52.945 -    ERROR : Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/routers/html.py", line 26, in usage_point_id
    return UsagePoint(usage_point_id).display()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 305, in display
    datatable = str(self.get_price("consumption"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 907, in get_price
    html += generate_price_compare(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 857, in generate_price_compare
    evolution_2 = round(data["price_3"] - data["price_1"], 2)
                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
2024-02-02 23:05:56.530 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-02 23:05:56.530 -     INFO : REFRESH ORM OBJECTS
2024-02-02 23:05:56.530 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-02 23:05:56.685 -     INFO : 172.28.0.3:59176 - "GET /usage_point_id/50067238117598 HTTP/1.1" 500
2024-02-02 23:05:56.686 -    ERROR : Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/routers/html.py", line 26, in usage_point_id
    return UsagePoint(usage_point_id).display()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 305, in display
    datatable = str(self.get_price("consumption"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 907, in get_price
    html += generate_price_compare(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 857, in generate_price_compare
    evolution_2 = round(data["price_3"] - data["price_1"], 2)
                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

<details>
<summary>Configuration (config.yaml)</summary>

```
home_assistant_ws:
  enable: true
  ssl: true
  token: ***
  url: ***
influxdb:
  enable: true
  hostname: influxdb
  port: 8086
  token: ***
  org: Personal
  bucket: myelectricaldata
  method: batching
  batching_options:
    batch_size: 1000
    flush_interval: 1000
    jitter_interval: 0
    retry_interval: 5000
    max_retry_time: 180_000
    max_retries: 5
    max_retry_delay: 125_000
    exponential_base: 2
mqtt:
  enable: true
  hostname: host.docker.internal
  port: 1883
  username: ***
  password: ***
  prefix: myelectricaldata
  client_id: myelectricaldata
  retain: true
  qos: 0

myelectricaldata:
  "***":
    enable: 'true'
    token: ***
    name: "Maison"
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.228'
    consumption_price_hc: "0.1464"
    consumption_price_hp: "0.2460"
    consumption_max_date: "2022-04-01"
    consumption_detail_max_date: "2022-04-01"
    offpeak_hours_0: 20H00-8H00;13H00-18H00   # LUNDI
    offpeak_hours_1: 20H00-8H00;13H00-18H00   # MARDI
    offpeak_hours_2: 20H00-8H00;13H00-18H00   # MERCREDI
    offpeak_hours_3: 20H00-8H00;13H00-18H00   # JEUDI
    offpeak_hours_4: 20H00-8H00;13H00-18H00   # VENDREDI
    offpeak_hours_5: 22H00-6H00;12H00-14H00   # SAMEDI
    offpeak_hours_6: 20H00-8H00;13H00-18H00   # DIMANCHE
    plan: "HP/HC"
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    production_max_date: "2022-04-01"
    production_detail_max_date: "2022-04-01"
    refresh_addresse: 'false'
    refresh_contract: 'false'
```
</details>

**Type d'installation**

- [X] Docker
- [ ] HassIO

**Version : [0.10.0-rc.22](https://github.com/MyElectricalData/myelectricaldata_import/releases/tag/v0.10.0-rc.22)**

**Comment by WarC0zes** [comment]
Bonjour,
même problème sur la version 0.10.0. quand en veut lire les données depuis le dashboard MED.

Installation HAOS.
```
2024-02-10 05:36:57.818 -    ERROR : Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/routers/html.py", line 26, in usage_point_id
    return UsagePoint(usage_point_id).display()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 305, in display
    datatable = str(self.get_price("consumption"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 907, in get_price
    html += generate_price_compare(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 857, in generate_price_compare
    evolution_2 = round(data["price_3"] - data["price_1"], 2)
                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
```

**Comment by m4dm4rtig4n** [comment]
Hello est-ce que vous avez également le soucis avec la 0.11.0-RC ?

**Comment by poilaunez** [comment]
@m4dm4rtig4n j'avais le même souci, la RC corrige le souci, merci !

**Comment by cvalentin-dkt** [comment]
Il y avait encore un petit soucis, et le fix arrive avec la 0.11.0-rc.2.

**Comment by WarC0zes** [comment]
Désoler pas tester la RC, trop la flemme de changer de version. Mais je vois que tu as trouver le problème, je vais attendre la version stable. Merci pour les fix.

**Comment by Jeepmg** [comment]
Bonjour, 

Je ne compends pas pourquoi cette discussion est close alors que le souci va arriver à tous ceux qui vont installer le V 10 ce samedi.

Si je comprends bien, soit on attend samedi prochain pour avoir la version stable à jour, soit on installe un version dev que l'on enlève samedi prochain.

Merci pour tout.

**Comment by m4dm4rtig4n** [comment]
Pour le coup je l'ai clos involontairement :D

**Comment by Gandulf78** [comment]
Ne plante plus avec la RC2!

**Comment by Dites33** [comment]
Bonjour

Même problème avec la mise à jour ce matin, puis je installer la RC2 ? Comment procéder si on passe par l'addon en général ?

**Comment by cvalentin-dkt** [comment]
> Bonjour
> 
> Même problème avec la mise à jour ce matin, puis je installer la RC2 ? Comment procéder si on passe par l'addon en général ?

Pour l'addons je suis dépendant d'Alexbelbium qui build les addons 1 fois par semaine le samedi.
Il faudrait que je regarde comment ca fonctionne au pire pour proposer directement l'addon ici mais encore eu le temps de le faire.

**Comment by m4dm4rtig4n** [comment]
Avec la 0.11.0 vous avez encore des soucis ?

**Comment by WarC0zes** [comment]
> Avec la 0.11.0 vous avez encore des soucis ?

Salut,
plus de soucis avec la 0.11.0, je peu voir les informations dans le dashboard MED.

**Comment by Dites33** [comment]
Tout ok pour moi aussi ! Merci :)

**Comment by m4dm4rtig4n** [comment]
Nickel je clos l'issue :)

**Comment by Gandulf78** [comment]
Tout est ok pour moi aussi. Merci.
