### ISSUE TITLE
[BUG] - HP / HC du mois non remis à zéro dans MQTT

### ISSUE THREAD

**Issue by loicdelecroix** [MyElectricalData/myelectricaldata_import#480]
**Description du bug**
Bonjour,
Depuis le début du mois, les données HP / HC présents dans MQTT dans le topic "thisMonth" ne sont pas remis à zéro, mais restent sur la valeur du mois précédent; par contre pour le tarif de base, c'est bien la bonne valeur qui remonte.
![bug1](https://github.com/MyElectricalData/myelectricaldata_import/assets/45817385/ed8e8fd3-49b3-48c8-b5da-0ac5943d6009)

Idem dans la section "month" où les valeurs pour le mois courant restent à 0
![bug2](https://github.com/MyElectricalData/myelectricaldata_import/assets/45817385/729dd408-a34a-4eeb-ae18-728f7b01e319)

A voir si c'est lié, mais j'ai cette erreur dans les logs quand je démarre l'add-on :
```log
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-03 12:23:18.727 -     INFO : [XXXXXXXXXXXX] EXPORT MQTT
2024-02-03 12:23:18.727 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-03 12:23:18.727 -     INFO : Statut du compte.
2024-02-03 12:23:18.731 -     INFO :  => OK
2024-02-03 12:23:18.731 -     INFO : Génération des messages du contrat
2024-02-03 12:23:18.737 -     INFO :  => OK
2024-02-03 12:23:18.738 -     INFO : Génération des messages d'addresse
2024-02-03 12:23:18.742 -     INFO :  => OK
2024-02-03 12:23:18.742 -     INFO : Génération des données Ecowatt
2024-02-03 12:23:18.749 -     INFO :  => OK
2024-02-03 12:23:18.749 -     INFO : Envoie des données Tempo
2024-02-03 12:23:18.778 -     INFO :  => OK
2024-02-03 12:23:18.779 -     INFO : Génération des données annuelles
Traceback (most recent call last):
  File "/app/models/jobs.py", line 543, in export_mqtt
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 508, in run
    export_mqtt.daily_annual(usage_point_config.consumption_price_base,
  File "/app/models/export_mqtt.py", line 115, in daily_annual
    get_daily_week = stat.get_week(year=year)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/models/stat.py", line 603, in get_week
    now_date.replace(year=year, month=month, day=int(start.strftime("%d"))),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: day is out of range for month
2024-02-03 12:23:18.985 -    ERROR : Erreur lors de la export mqtt
2024-02-03 12:23:18.985 -    ERROR : day is out of range for month
2024-02-03 12:23:18.985 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ 
```

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
port: 5000
debug: true
log2file: false
tempo:
  enable: false
influxdb:
  enable: false
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
home_assistant_ws:
  enable: true
  ssl: false
  token: XXXXXXXXX
  url: "XXXXXXX"
mqtt:
  enable: true
  hostname: core-mosquitto
  port: 1883
  username: XXXXXX
  password: XXXXXX
  prefix: myelectricaldata
  client_id: myelectricaldata
  retain: true
  qos: 0
myelectricaldata:
  "XXXXXXXXXX":
    enable: "true"
    token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    name: XXXXXXXX
    addresses: "false"
    cache: "true"
    consumption: "true"
    consumption_detail: "true"
    consumption_price_base: "0.2276"
    consumption_price_hc: "0.1828"
    consumption_price_hp: "0.2460"
    offpeak_hours_0: 1H00-7H00;12H30-14H30
    offpeak_hours_1: 1H00-7H00;12H30-14H30
    offpeak_hours_2: 1H00-7H00;12H30-14H30
    offpeak_hours_3: 1H00-7H00;12H30-14H30
    offpeak_hours_4: 1H00-7H00;12H30-14H30
    offpeak_hours_5: 1H00-7H00;12H30-14H30
    offpeak_hours_6: 1H00-7H00;12H30-14H30
    plan: HC/HP
    production: "false"
    production_detail: "false"
    production_price: "0.0"
    production_max_date: "2021-06-01"
    production_detail_max_date: "2021-06-01"
    refresh_addresse: "false"
    refresh_contract: "false"
```
</details>

**Type d'installation**

- [ ] Docker
- [X] HassIO

**Version : 0.9.3**

Dispo si besoin de plus d'infos

**Comment by loicdelecroix** [comment]
Hello,

Aujourd'hui, les données remontées sont bonnes ! 
Vu le log d’erreur, et le fait que ça se soit fix tout seul un lundi matin, peut être un soucis quand on change de mois au cours de la même semaine ?

**Comment by m4dm4rtig4n** [comment]
Hello,

Tu n'aurai pas upgrade de version ?
C'est fix à partir de la 0.10.0-RC.X

**Comment by loicdelecroix** [comment]
Hello,

Au moment de mon commentaire il y a 3j, j'étais encore sur la version stable (0.9.3)
Tant mieux si c'est fix sur la prochaine version, je regarderai au début du mois prochain si tout est ok ! :)

Merci pour le taff effectué sur cette passerelle !

**Comment by m4dm4rtig4n** [comment]
Hello @loicdelecroix tu as pu tester le fix ?

**Comment by loicdelecroix** [comment]
Hello,

En fait, le problème s'est résolu de lui-même lundi dernier, et depuis, pas eu de soucis (j'étais encore sur la 0.9.3)
J'avais l'impression que ça n'arrivait qu'en début de mois, donc je regarderais début mars si tout est OK :)

Tu peux clore l'issue je pense, je ré ouvrirai si besoin le mois prochain
