### ISSUE TITLE
[HELP] - No data - Internal Server Error on WebUI

### ISSUE THREAD

**Issue by fishter** [MyElectricalData/myelectricaldata_import#497]
**Description de la fonctionnalité**
Depuis le 11 fevrier j'ai aucune data consommation sur mon Energy Dashboard.  J'ai regardee le WebUI mais aprés je chois le PDL: "Internal Server Error"
Je verifié les PDL et token/clé d'accès:
curl -X GET "https://www.myelectricaldata.fr/valid_access/21152243110863" -H "Authorization: <clé>"
{"valid":true,"information":"","consent_expiration_date":"2027-02-16T09:48:49","call_number":10,"quota_reached":false,"quota_limit":50,"quota_reset_at":"2024-02-16T23:59:59.999999","last_call":"2023-11-07T11:22:47.316663","ban":false}

**Type d'installation**
HassIO

**Version : 0.10.0**
Home Assistant: Core 2024.2.1, Supervisor 2024.01.1, HAOS 11.5, Frontend 20240207.1

Config:

```
cycle: 14400
debug: true
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
influxdb:
  batching_options:
    batch_size: 1000
    exponential_base: 2
    flush_interval: 1000
    jitter_interval: 0
    max_retries: 5
    max_retry_delay: 125000
    max_retry_time: 180000
    retry_interval: 10000
  bucket: myelectricaldata
  enable: false
  hostname: influxdb
  method: synchronous
  org: myelectricaldata
  port: 8086
  token: myelectricaldata
log2file: false
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: core-mosquitto
  password: 
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: addons
myelectricaldata:
  'PID':
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_max_power: 'true'
    consumption_price_base: '0.175'
    consumption_price_hc: '0.2068'
    consumption_price_hp: '0.2700'
    enable: 'true'
    name: maison 35B
    offpeak_hours_0: 22h56-06h56
    offpeak_hours_1: 22h56-06h56
    offpeak_hours_2: 22h56-06h56
    offpeak_hours_3: 22h56-06h56
    offpeak_hours_4: 22h56-06h56
    offpeak_hours_5: 22h56-06h56
    offpeak_hours_6: 22h56-06h56
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0'
    refresh_addresse: 'true'
    refresh_contract: 'true'
    token: 
tempo:
  enable: false
  price_blue_hc: 0.097
  price_blue_hp: 0.1249
  price_red_hc: 0.1216
  price_red_hp: 0.6712
  price_white_hc: 0.114
  price_white_hp: 0.1508
wipe_influxdb: false
```

Log:

```
2024-02-16 09:53:02.007 -     INFO : 127.0.0.1:37362 - "GET / HTTP/1.1" 200
2024-02-16 09:53:06.747 -     INFO : 172.30.32.1:0 - "GET / HTTP/1.1" 200
[16/Feb/2024:09:53:06 +0100] 200 <IP>, 192.168.1.54, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36)
2024-02-16 09:53:06.931 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-16 09:53:06.931 -     INFO : CHECK DE L'ÉTAT DE LA PASSERELLE.
2024-02-16 09:53:06.932 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-16 09:53:07.066 -     INFO : status: True
2024-02-16 09:53:07.066 -     INFO : information: None
2024-02-16 09:53:07.066 -     INFO : nb_client: 2278
2024-02-16 09:53:07.066 -     INFO : waiting_estimation: 0.0s
2024-02-16 09:53:07.076 -     INFO : 172.30.32.1:0 - "GET /gateway_status/ HTTP/1.1" 200
[16/Feb/2024:09:53:07 +0100] 200 <IP>, 192.168.1.54, 172.30.32.1(172.30.32.2) GET /gateway_status/ HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36)
2024-02-16 09:53:07.192 -     INFO : 127.0.0.1:38414 - "GET / HTTP/1.1" 200
[16/Feb/2024:09:53:07 +0100] 200 <IP>, 192.168.1.54, 172.30.32.1(172.30.32.2) GET /import_status HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36)
2024-02-16 09:53:08.802 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-16 09:53:08.803 -     INFO : REFRESH ORM OBJECTS
2024-02-16 09:53:08.803 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-16 09:53:09.002 -     INFO : 172.30.32.1:0 - "GET /usage_point_id/PID HTTP/1.1" 500
2024-02-16 09:53:09.003 -    ERROR : Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/routers/html.py", line 26, in usage_point_id
    return UsagePoint(usage_point_id).display()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 305, in display
    datatable = str(self.get_price("consumption"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 907, in get_price
    html += generate_price_compare(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 857, in generate_price_compare
    evolution_2 = round(data["price_3"] - data["price_1"], 2)
                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
[16/Feb/2024:09:53:09 +0100] 500 <IP>, 192.168.1.54, 172.30.32.1(172.30.32.2) GET /usage_point_id/PID HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36)
2024-02-16 09:53:12.342 -     INFO : 127.0.0.1:38444 - "GET / HTTP/1.1" 200
```

**Comment by fishter** [comment]
I see no update available in the HassIO add-on store entry yet. I guess I'll just wait until it's released.
