### ISSUE TITLE
[BUG] - Erreur lors du bootstrap mais qui ne (semble) pas géner la remontée des données

### ISSUE THREAD

**Issue by r-jean-pierre** [MyElectricalData/myelectricaldata_import#524]
**Description du bug**
Lors de la mise en route de l'add-on, on peut voir dans les logs:

```
2024-04-24 13:35:22.012 -     INFO :  Chargement des données depuis MyElectricalData 2024-02-16 => 2024-02-23
2024-04-24 13:35:22.522 -     INFO : 127.0.0.1:41198 - "GET / HTTP/1.1" 200
2024-04-24 13:35:23.310 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/query_detail.py", line 119, in run
    for interval_reading in meter_reading["interval_reading"]:
                            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-04-24 13:35:23.312 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/jobs.py", line 287, in get_consumption_detail
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 276, in run
    Detail(headers=self.header_generate(), usage_point_id=usage_point_id).get()
  File "/app/models/query_detail.py", line 201, in get
    if "exit" in response:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2024-04-24 13:35:23.317 -    ERROR : Erreur lors de la récupération de la consommation détaillée
2024-04-24 13:35:23.318 -    ERROR : argument of type 'NoneType' is not iterable
```

Je ne sais pas si ça engendre des erreurs plus tard ou des choses que j'aurais du avoir/voir, mais ça ne semble pas être critique pour avoir la page enedisgateway2mqtt/ingress avec un max d’informations

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400
debug: true
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
influxdb:
  batching_options:
    batch_size: 1000
    exponential_base: 2
    flush_interval: 1000
    jitter_interval: 0
    max_retries: 5
    max_retry_delay: 125000
    max_retry_time: 180000
    retry_interval: 5000
  bucket: homeassistant/autogen
  enable: true
  hostname: a0d7b954-influxdb
  method: synchronous
  org: '-'
  port: 8086
  scheme: http
  token: ***
log2file: false
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: localhost
  password: null
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: null
myelectricaldata:
  ***:
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: '2021-06-01'
    consumption_max_date: '2021-06-01'
    consumption_max_power: 'true'
    consumption_price_base: '0.2795'
    consumption_price_hc: '0.1927'
    consumption_price_hp: '0.2795'
    enable: 'true'
    name: Maison
    offpeak_hours_0: 22H00-6H00
    offpeak_hours_1: 22H00-6H00
    offpeak_hours_2: 22H00-6H00
    offpeak_hours_3: 22H00-6H00
    offpeak_hours_4: 22H00-6H00
    offpeak_hours_5: 22H00-6H00
    offpeak_hours_6: 22H00-6H00
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: '2021-06-01'
    production_max_date: '2021-06-01'
    production_price: '0.0'
    refresh_addresse: 'true'
    refresh_contract: 'true'
    token: ***
tempo:
  enable: false
  price_blue_hc: 0.097
  price_blue_hp: 0.1249
  price_red_hc: 0.1216
  price_red_hp: 0.6712
  price_white_hc: 0.114
  price_white_hp: 0.1508
wipe_influxdb: false

```
</details>

**Type d'installation**

- [*] Docker
- [ ] HassIO

**Version : 0.12.0**

Merci pour l'add-on que je viens de découvrir. Il me reste juste à manager mqtt pour avoir le sensor dans HA, mais j'ai déjà mon InfluxDb

**Comment by wallforfry** [comment]
Bonjour,
Même problème pour ma part et aucune donnée ne remonte (pas de conso journalière, détaillée, ou puissance maxi)

```
2024-07-20 13:28:17.401 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-07-20 13:28:17.402 -     INFO : [22487698876941] RÉCUPÉRATION DE LA CONSOMMATION JOURNALIÈRE :
2024-07-20 13:28:17.402 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-07-20 13:28:17.408 -     INFO : Récupération des données : 2021-07-23 => 2024-07-22
2024-07-20 13:28:19.587 -     INFO :  Chargement des données depuis MyElectricalData 2021-07-23 => 2024-07-22
2024-07-20 13:28:24.065 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/query_daily.py", line 154, in run
    interval_reading = meter_reading["interval_reading"]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-07-20 13:28:24.065 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/jobs.py", line 256, in get_consumption
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 245, in run
    Daily(headers=self.header_generate(), usage_point_id=usage_point_id).get()
  File "/app/models/query_daily.py", line 244, in get
    if "exit" in response:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2024-07-20 13:28:24.067 -    ERROR : Erreur lors de la récupération de la consommation journalière
2024-07-20 13:28:24.067 -    ERROR : argument of type 'NoneType' is not iterable
2024-07-20 13:28:24.067 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-07-20 13:28:24.067 -     INFO : ▌│█║▌║▌║       ___                                 _     _____  _         _       _      _  _  _       ║▌║▌║█│▌
2024-07-20 13:28:24.067 -     INFO : ▌│█║▌║▌║      |_ _| _ __ ___   _ __    ___   _ __ | |_  |  ___|(_) _ __  (_) ___ | |__  | || || |      ║▌║▌║█│▌
2024-07-20 13:28:24.067 -     INFO : ▌│█║▌║▌║       | | | '_ ` _ \ | '_ \  / _ \ | '__|| __| | |_   | || '_ \ | |/ __|| '_ \ | || || |      ║▌║▌║█│▌
2024-07-20 13:28:24.067 -     INFO : ▌│█║▌║▌║       | | | | | | | || |_) || (_) || |   | |_  |  _|  | || | | || |\__ \| | | ||_||_||_|      ║▌║▌║█│▌
2024-07-20 13:28:24.067 -     INFO : ▌│█║▌║▌║      |___||_| |_| |_|| .__/  \___/ |_|    \__| |_|    |_||_| |_||_||___/|_| |_|(_)(_)(_)      ║▌║▌║█│▌
2024-07-20 13:28:24.068 -     INFO : ▌│█║▌║▌║                      |_|                                                                      ║▌║▌║█│▌
2024-07-20 13:28:24.068 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by m4dm4rtig4n** [comment]
Tt est de nouveau opérationnel dont les 2 endpoints addresses & contract.

=> Je clos l'issue :)
