### ISSUE TITLE
[BUG] - ERROR : division by zero

### ISSUE THREAD

**Issue by roumano** [MyElectricalData/myelectricaldata_import#542]
**Description du bug**
Juste use my cache.db ( you can found in discord direct chat form Roumano ) 

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400  # 4H
debug: false
wipe_influxdb: false
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
influxdb:
  enable: false
mqtt:
  enable: true
  hostname: 192.168.1.15
  port: 1883
  username: pi
  password: Rasta101
  prefix: myelectricaldata
  client_id: myelectricaldata     # DOIT ETRE UNIQUE SUR LA TOTALITE DES CLIENTS CONNECTE AU SERVEUR MQTT
  retain: true
  qos: 0
myelectricaldata:
  "19346888530116":
    enable: 'true'
    token: xxxxx
    name: "Maison"
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.1740'
    consumption_max_date: "2024-03-10"
    consumption_detail_max_date: "2024-03-10"
    plan: TEMPO
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    production_max_date: "2024-03-01"
    production_detail_max_date: "2024-03-01"
    refresh_addresse: 'false'
    refresh_contract: 'false'
tempo:
  enable: true
```
</details>

**Type d'installation**

- [x] Docker
- [ ] HassIO

**Version : 12.0 for me and also 13.1 confirmed by microdav **

mon log : 
```
2024-04-10 16:22:12.210 -     INFO : Génération des données de puissance max journalières.
Traceback (most recent call last):
  File "/app/models/jobs.py", line 566, in export_mqtt
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 556, in run
    export_mqtt.max_power()
  File "/app/models/export_mqtt.py", line 414, in max_power
    threshold_usage = int(100 * value_w / max_value)
                          ~~~~~~~~~~~~~~^~~~~~~~~~~
ZeroDivisionError: division by zero
2024-04-10 16:22:12.279 -    ERROR : Erreur lors de la export mqtt
2024-04-10 16:22:12.279 -    ERROR : division by zero
```

log de microdav : 
```

2024-05-29 12:09:54.061 -     INFO : Génération des données de puissance max journalières.
Traceback (most recent call last):
  File "/app/models/jobs.py", line 559, in export_mqtt
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 549, in run
    export_mqtt.max_power()
  File "/app/models/export_mqtt.py", line 414, in max_power
    threshold_usage = int(100 * value_w / max_value)
                          ~~~~^~~~~
ZeroDivisionError: division by zero
2024-05-29 12:09:54.096 -    ERROR : Erreur lors de la export mqtt
2024-05-29 12:09:54.097 -    ERROR : division by zero
```

In discord chan, see at least 3 other person get the same bug/issue

**Comment by Sylv1F** [comment]
idem en 0.13.2

Home Assistant

Core 2024.5.5
Supervisor 2024.05.1
Operating System 12.3
Interface utilisateur 20240501.1


2024-05-30 14:56:14.844 -     INFO : Génération des données de puissance max journalières.
Traceback (most recent call last):
  File "/app/models/jobs.py", line 559, in export_mqtt
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 549, in run
    export_mqtt.max_power()
  File "/app/models/export_mqtt.py", line 414, in max_power
    threshold_usage = int(100 * value_w / max_value)
                          ~~~~~~~~~~~~~~^~~~~~~~~~~
ZeroDivisionError: division by zero
2024-05-30 14:56:14.902 -    ERROR : Erreur lors de la export mqtt
2024-05-30 14:56:14.902 -    ERROR : division by zero

**Comment by m4dm4rtig4n** [comment]
Je viens de fix et sera en ligne avec la prochaine RC
