### ISSUE TITLE
[BUG] - Erreur lors de la remontée des infos de production seulement

### ISSUE THREAD

**Issue by kpagnat** [MyElectricalData/myelectricaldata_import#585]
**Description du bug**
Après avoir galéré pour refaire mon consentement auprès d'Enedis, j'ai enfin pu refaire tourner ce module et récupérer toutes mes données de consommation. Cependant, je me souviens qu'auparavant, je récupérais également mes données de production et injection (panneaux solaires).

En regardant le log du module, j'ai trouvé cette erreur (j'ai remplacé le PDL et les mots de passe par XXXXXX) :
Tout le reste fonctionne parfaitement.

```
2024-12-13 07:06:24.318 -     INFO : Effacement des données importées dans Energy.
2024-12-13 07:06:24.318 -     INFO :  - myelectricaldata:XXXXXXXXXXXXX_production
2024-12-13 07:06:28.250 -     INFO : 127.0.0.1:49058 - "GET / HTTP/1.1" 200
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/websocket/_socket.py", line 118, in recv
    bytes_ = _recv()
             ^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_socket.py", line 97, in _recv
    return sock.recv(bufsize)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1233, in recv
    return self.read(buflen)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1106, in read
    return self._sslobj.read(len)
           ^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/models/export_home_assistant_ws.py", line 496, in import_data
    self.clear_data(list_statistic_ids)
  File "/app/models/export_home_assistant_ws.py", line 181, in clear_data
    clear_stat = self.send(clear_statistics)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/models/export_home_assistant_ws.py", line 138, in send
    output = json.loads(self.websocket.recv())
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_core.py", line 388, in recv
    opcode, data = self.recv_data()
                   ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_core.py", line 416, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_core.py", line 437, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_core.py", line 478, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_abnf.py", line 363, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python3.12/site-packages/websocket/_abnf.py", line 319, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_abnf.py", line 398, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_core.py", line 563, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_socket.py", line 120, in recv
    raise WebSocketTimeoutException("Connection timed out")
websocket._exceptions.WebSocketTimeoutException: Connection timed out
2024-12-13 07:06:29.337 -    ERROR : Connection timed out
2024-12-13 07:06:29.337 - CRITICAL : Erreur lors de l'export des données vers Home Assistant
```

**config.yaml**

```
cycle: 14400 # 4H
debug: true
log2file: false
wipe_influxdb: false # Work only with influxdb > 2.X
# Par défaut le backend en local dans le /data/cache.db du conteneur.
# Mais il est possible de basculer sur une base de données externe de type SQLite ou PostgreSQL
# Exemple pour Postgres :
# storage_uri: postgresql://myelectricaldata:myelectricaldata@postgres:5432/myelectricaldata
mqtt:
  enable: true
  hostname: core-mosquitto
  port: 1883
  username: mqtt
  password: XXXXXX
  prefix: myelectricaldata
  client_id: myelectricaldata # DOIT ETRE UNIQUE SUR LA TOTALITE DES CLIENTS CONNECTE AU SERVEUR MQTT
  retain: true
  qos: 0
home_assistant: # MQTT est obligaoire pour Home Assistant
  enable: true
  discovery: true
  discovery_prefix: homeassistant
home_assistant_ws:
  enable: true
  ssl: true
  token: XXXXXX
  url: HA_URL
influxdb:
  enable: false
  hostname: influxdb
  port: 8086
  token: myelectricaldata
  org: myelectricaldata
  bucket: myelectricaldata
  # ATTENTION, L'activation de l'importation asynchrone va réduire fortement le temps d'importation dans InfluxDB
  # mais va augmenter la consommation mémoire & CPU et donc à activer uniquement sur un hardware robuste.
  method: synchronous # Mode disponible : synchronous / asynchronous / batching
  # batching_options permet uniquement de configurer la methode `batching`.
  # Pour plus d'information : https://github.com/influxdata/influxdb-client-python#batching
  batching_options:
    batch_size: 1000
    flush_interval: 1000
    jitter_interval: 0
    retry_interval: 5000
    max_retry_time: 180_000
    max_retries: 5
    max_retry_delay: 125_000
    exponential_base: 2
myelectricaldata:
  "XXXXXXX":
    enable: "true"
    token: "XXXXXXXXX"
    name: "Home"
    addresses: "true"
    cache: "true"
    consumption: "true"
    consumption_detail: "true"
    consumption_price_base: "0.145907"
    consumption_price_hc: "0.124364"
    consumption_price_hp: "0.164915"
    consumption_max_date: "2021-06-01"
    consumption_detail_max_date: "2021-06-01"
    offpeak_hours_0: 22H00-6H00 # LUNDI
    offpeak_hours_1: 22H00-6H00 # MARDI
    offpeak_hours_2: 22H00-6H00 # MERCREDI
    offpeak_hours_3: 22H00-6H00 # JEUDI
    offpeak_hours_4: 22H00-6H00 # VENDREDI
    offpeak_hours_5: 22H00-6H00;12H00-14H00 # SAMEDI
    offpeak_hours_6: 22H00-6H00;12H00-14H00 # DIMANCHE
    plan: TEMPO
    production: "true"
    production_detail: "true"
    production_price: "0.11"
    production_max_date: "2024-01-01"
    production_detail_max_date: "2024-01-01"
    refresh_addresse: "false"
    refresh_contract: "false"
```

Une idée ? Quelque chose que je dois faire de mon côté ?

**Type d'installation**

- [ ] Docker
- [X ] HassIO

**Version : 0.13.2*

**Comment by kpagnat** [comment]
Oups ... merci ;)
Et du coup, c'est quoi le conteneur MED et que puis-je faire ? :D

**Comment by m4dm4rtig4n** [comment]
Si tu est sur haos, il faut mettre l'url interne de ton HA et ne pas passer par ton domaine public (mais je ne la connais par contre, je ne suis pas sur haos :/)

**Comment by kpagnat** [comment]
Okay, j'ai réussi à corriger les informations pour le WebSocket et maintenant j'ai le message 
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-12-13 12:24:06.427 -     INFO : [XXXXX] IMPORT DES DONNÉES VERS L'ONGLET ENERGY DE HOME ASSISTANT (WEBSOCKET)
2024-12-13 12:24:06.428 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-12-13 12:24:06.434 -     INFO : Connexion au WebSocket Home Assistant ws://XXXXX:8123/api/websocket
2024-12-13 12:24:06.441 -     INFO : Authentification requise
2024-12-13 12:24:06.443 -     INFO :  => OK
2024-12-13 12:24:06.443 -     INFO : Importation des données du point de livraison : XXXXXX
```

Ca, c'est okay, mais j'ai toujours la même erreur un peu plus loin :
```
2024-12-13 12:24:11.437 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-12-13 12:24:11.438 -     INFO : REFRESH ORM OBJECTS
2024-12-13 12:24:11.438 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-12-13 12:24:11.438 -     INFO : Envoi des données de conso REDHC vers Home Assistant 1/1 (2024-12-12T23:00:00+01:00 => 2022-12-13T00:00:00+01:00)
2024-12-13 12:24:11.462 -     INFO : - sensor.linky_XXXXX_redhc_consumption
2024-12-13 12:24:11.467 -     INFO : Envoi des données de conso REDHP vers Home Assistant 1/1 (2024-12-12T21:00:00+01:00 => 2022-12-13T06:00:00+01:00)
2024-12-13 12:24:11.506 -     INFO : - sensor.linky_XXXXX_redhp_consumption
2024-12-13 12:24:11.512 -     INFO : Envoi des données de conso WHITEHP vers Home Assistant 1/2 (2024-04-24T13:00:00+02:00 => 2022-12-15T06:00:00+01:00)
2024-12-13 12:24:11.549 -     INFO : Envoi des données de conso WHITEHP vers Home Assistant 2/2 (2024-12-09T21:00:00+01:00 => 2024-04-24T14:00:00+02:00)
2024-12-13 12:24:11.572 -     INFO : - sensor.linky_XXXXX_whitehp_consumption
2024-12-13 12:24:11.576 -     INFO : Envoi des données de conso WHITEHC vers Home Assistant 1/1 (2024-12-10T05:00:00+01:00 => 2022-12-15T22:00:00+01:00)
2024-12-13 12:24:11.621 -     INFO : - sensor.linky_XXXXX_whitehc_consumption
2024-12-13 12:24:11.625 -     INFO : Envoi des données de conso BLUEHP vers Home Assistant 1/10 (2023-04-10T13:00:00+02:00 => 2022-12-18T06:00:00+01:00)
2024-12-13 12:24:11.665 -     INFO : Envoi des données de conso BLUEHP vers Home Assistant 2/10 (2023-06-18T21:00:00+02:00 => 2023-04-10T14:00:00+02:00)
2024-12-13 12:24:11.687 -     INFO : Envoi des données de conso BLUEHP vers Home Assistant 3/10 (2023-08-20T13:00:00+02:00 => 2023-06-19T06:00:00+02:00)
2024-12-13 12:24:11.742 -     INFO : Envoi des données de conso BLUEHP vers Home Assistant 4/10 (2023-10-21T21:00:00+02:00 => 2023-08-20T14:00:00+02:00)
2024-12-13 12:24:11.772 -     INFO : Envoi des données de conso BLUEHP vers Home Assistant 5/10 (2024-01-23T13:00:00+01:00 => 2023-10-22T06:00:00+02:00)
2024-12-13 12:24:11.824 -     INFO : Envoi des données de conso BLUEHP vers Home Assistant 6/10 (2024-04-29T07:00:00+02:00 => 2024-01-23T14:00:00+01:00)
2024-12-13 12:24:11.879 -     INFO : Envoi des données de conso BLUEHP vers Home Assistant 7/10 (2024-06-30T15:00:00+02:00 => 2024-04-29T08:00:00+02:00)
2024-12-13 12:24:11.920 -     INFO : Envoi des données de conso BLUEHP vers Home Assistant 8/10 (2024-09-01T07:00:00+02:00 => 2024-06-30T16:00:00+02:00)
2024-12-13 12:24:11.955 -     INFO : Envoi des données de conso BLUEHP vers Home Assistant 9/10 (2024-11-02T15:00:00+01:00 => 2024-09-01T08:00:00+02:00)
2024-12-13 12:24:12.017 -     INFO : Envoi des données de conso BLUEHP vers Home Assistant 10/10 (2024-12-08T21:00:00+01:00 => 2024-11-02T16:00:00+01:00)
2024-12-13 12:24:12.063 -     INFO : - sensor.linky_XXXXX_bluehp_consumption
2024-12-13 12:24:12.090 -     INFO : Envoi des données de conso BLUEHC vers Home Assistant 1/5 (2023-06-20T03:00:00+02:00 => 2022-12-18T22:00:00+01:00)
2024-12-13 12:24:12.184 -     INFO : Envoi des données de conso BLUEHC vers Home Assistant 2/5 (2023-10-23T04:00:00+02:00 => 2023-06-20T04:00:00+02:00)
2024-12-13 12:24:12.270 -     INFO : Envoi des données de conso BLUEHC vers Home Assistant 3/5 (2024-04-30T22:00:00+02:00 => 2023-10-23T05:00:00+02:00)
2024-12-13 12:24:12.333 -     INFO : 127.0.0.1:59182 - "GET / HTTP/1.1" 200
2024-12-13 12:24:12.347 -     INFO : Envoi des données de conso BLUEHC vers Home Assistant 4/5 (2024-09-02T22:00:00+02:00 => 2024-04-30T23:00:00+02:00)
2024-12-13 12:24:12.402 -     INFO : Envoi des données de conso BLUEHC vers Home Assistant 5/5 (2024-12-09T05:00:00+01:00 => 2024-09-02T23:00:00+02:00)
2024-12-13 12:24:12.454 -     INFO : - sensor.linky_XXXXX_bluehc_consumption
2024-12-13 12:24:12.458 -     INFO : Envoi des données de coût REDHC vers Home Assistant 1/1 (2022-12-13T00:00:00+01:00 => 2024-12-12T23:00:00+01:00)
2024-12-13 12:24:12.509 -     INFO : - sensor.linky_XXXXX_redhc_consumption_cost
2024-12-13 12:24:12.516 -     INFO : Envoi des données de coût REDHP vers Home Assistant 1/1 (2022-12-13T06:00:00+01:00 => 2024-12-12T21:00:00+01:00)
2024-12-13 12:24:12.559 -     INFO : - sensor.linky_XXXXX_redhp_consumption_cost
2024-12-13 12:24:12.562 -     INFO : Envoi des données de coût WHITEHP vers Home Assistant 1/2 (2022-12-15T06:00:00+01:00 => 2024-04-24T13:00:00+02:00)
2024-12-13 12:24:12.613 -     INFO : Envoi des données de coût WHITEHP vers Home Assistant 2/2 (2024-04-24T14:00:00+02:00 => 2024-12-09T21:00:00+01:00)
2024-12-13 12:24:12.641 -     INFO : - sensor.linky_XXXXX_whitehp_consumption_cost
2024-12-13 12:24:12.647 -     INFO : Envoi des données de coût WHITEHC vers Home Assistant 1/1 (2022-12-15T22:00:00+01:00 => 2024-12-10T05:00:00+01:00)
2024-12-13 12:24:12.703 -     INFO : - sensor.linky_XXXXX_whitehc_consumption_cost
2024-12-13 12:24:12.707 -     INFO : Envoi des données de coût BLUEHP vers Home Assistant 1/10 (2022-12-18T06:00:00+01:00 => 2023-04-10T13:00:00+02:00)
2024-12-13 12:24:12.751 -     INFO : Envoi des données de coût BLUEHP vers Home Assistant 2/10 (2023-04-10T14:00:00+02:00 => 2023-06-18T21:00:00+02:00)
2024-12-13 12:24:12.792 -     INFO : Envoi des données de coût BLUEHP vers Home Assistant 3/10 (2023-06-19T06:00:00+02:00 => 2023-08-20T13:00:00+02:00)
2024-12-13 12:24:12.855 -     INFO : Envoi des données de coût BLUEHP vers Home Assistant 4/10 (2023-08-20T14:00:00+02:00 => 2023-10-21T21:00:00+02:00)
2024-12-13 12:24:12.917 -     INFO : Envoi des données de coût BLUEHP vers Home Assistant 5/10 (2023-10-22T06:00:00+02:00 => 2024-01-23T13:00:00+01:00)
2024-12-13 12:24:12.978 -     INFO : Envoi des données de coût BLUEHP vers Home Assistant 6/10 (2024-01-23T14:00:00+01:00 => 2024-04-29T07:00:00+02:00)
2024-12-13 12:24:13.033 -     INFO : Envoi des données de coût BLUEHP vers Home Assistant 7/10 (2024-04-29T08:00:00+02:00 => 2024-06-30T15:00:00+02:00)
2024-12-13 12:24:13.078 -     INFO : Envoi des données de coût BLUEHP vers Home Assistant 8/10 (2024-06-30T16:00:00+02:00 => 2024-09-01T07:00:00+02:00)
2024-12-13 12:24:13.126 -     INFO : Envoi des données de coût BLUEHP vers Home Assistant 9/10 (2024-09-01T08:00:00+02:00 => 2024-11-02T15:00:00+01:00)
2024-12-13 12:24:13.160 -     INFO : Envoi des données de coût BLUEHP vers Home Assistant 10/10 (2024-11-02T16:00:00+01:00 => 2024-12-08T21:00:00+01:00)
2024-12-13 12:24:13.198 -     INFO : - sensor.linky_XXXXX_bluehp_consumption_cost
2024-12-13 12:24:13.203 -     INFO : Envoi des données de coût BLUEHC vers Home Assistant 1/5 (2022-12-18T22:00:00+01:00 => 2023-06-20T03:00:00+02:00)
2024-12-13 12:24:13.266 -     INFO : Envoi des données de coût BLUEHC vers Home Assistant 2/5 (2023-06-20T04:00:00+02:00 => 2023-10-23T04:00:00+02:00)
2024-12-13 12:24:13.302 -     INFO : Envoi des données de coût BLUEHC vers Home Assistant 3/5 (2023-10-23T05:00:00+02:00 => 2024-04-30T22:00:00+02:00)
2024-12-13 12:24:13.334 -     INFO : Envoi des données de coût BLUEHC vers Home Assistant 4/5 (2024-04-30T23:00:00+02:00 => 2024-09-02T22:00:00+02:00)
2024-12-13 12:24:13.371 -     INFO : Envoi des données de coût BLUEHC vers Home Assistant 5/5 (2024-09-02T23:00:00+02:00 => 2024-12-09T05:00:00+01:00)
2024-12-13 12:24:13.428 -     INFO : - sensor.linky_XXXXX_bluehc_consumption_cost
2024-12-13 12:24:13.439 -     INFO : Production
2024-12-13 12:24:14.052 -     INFO : 2024 :
2024-12-13 12:24:14.055 -     INFO : - 3
2024-12-13 12:24:14.097 -     INFO : - 4
2024-12-13 12:24:14.226 -     INFO : - 5
2024-12-13 12:24:14.352 -     INFO : - 6
2024-12-13 12:24:14.554 -     INFO : - 7
2024-12-13 12:24:14.802 -     INFO : - 8
2024-12-13 12:24:15.051 -     INFO : - 9
2024-12-13 12:24:15.256 -     INFO : - 10
2024-12-13 12:24:15.477 -     INFO : - 11
2024-12-13 12:24:15.653 -     INFO : - 12
2024-12-13 12:24:15.736 -     INFO : Effacement des données importées dans Energy.
2024-12-13 12:24:15.736 -     INFO :  - myelectricaldata:XXXXXX_production
2024-12-13 12:24:17.491 -     INFO : 127.0.0.1:51444 - "GET / HTTP/1.1" 200
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/websocket/_socket.py", line 118, in recv
    bytes_ = _recv()
             ^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_socket.py", line 97, in _recv
    return sock.recv(bufsize)
           ^^^^^^^^^^^^^^^^^^
TimeoutError: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/models/export_home_assistant_ws.py", line 496, in import_data
    self.clear_data(list_statistic_ids)
  File "/app/models/export_home_assistant_ws.py", line 181, in clear_data
    clear_stat = self.send(clear_statistics)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/models/export_home_assistant_ws.py", line 138, in send
    output = json.loads(self.websocket.recv())
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_core.py", line 388, in recv
    opcode, data = self.recv_data()
                   ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_core.py", line 416, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_core.py", line 437, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_core.py", line 478, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_abnf.py", line 363, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python3.12/site-packages/websocket/_abnf.py", line 319, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_abnf.py", line 398, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_core.py", line 563, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_socket.py", line 120, in recv
    raise WebSocketTimeoutException("Connection timed out")
websocket._exceptions.WebSocketTimeoutException: Connection timed out
2024-12-13 12:24:20.757 -    ERROR : Connection timed out
2024-12-13 12:24:20.758 - CRITICAL : Erreur lors de l'export des données vers Home Assistant
```

Du coup, pas certain que ce soit finalement lié à Web Socket ...
La question que je me pose, c'est que je vois quand même des données dans mon onglet "Energie". Est-ce que j'ai besoin de "home_assistant_ws" finalement ?

**Comment by kpagnat** [comment]
Hum, en fait, oui, j'ai bien besoin de home_assistant_ws, car c'est lui qui crée les entités pour l'onglet Energie ... C'est pour cela que je retrouve bien les données de consommations (BLUEHC, BLUEHP,  etc..) mais que je n'ai rien pour l'injection.

**Comment by m4dm4rtig4n** [comment]
En fait je pense que le soucis vient du temps de traitement qui est trop long et tu fini par te prendre un timeout.
Essaie d'augmente fameux timeout, il me semble que d'autre utilisateur on déjà eu le soucis.

**Comment by kpagnat** [comment]
Merci pour ce retour qui semblait prometteur.

Cependant, après 2h de recherche, je n'ai pas trouvé où modifier ce timeout dans la configuration de home assistant.

**Comment by kpagnat** [comment]
En parcourant les différentes "issues", je viens de voir que mon problème correspond à celui là : #572 
Du coup, je clos cette issue là et me réfère à l'autre en espérant une résolution.
